### ISSUE TITLE
[EPIC] Nucleus 3.0 Docs

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#208]
## Outcome

Our docs have the right platform, content and setup to complement Nucleus 3.0

## Scope

- [x] https://github.com/centrica-engineering/nucleus/issues/423
- [x] #209
  - [x] spec
  - [x] details
- [x] Deprecate old links
  - [x] (Wikipedia-style redirects?)
- [x] #220

**Comment by RobTobias123** [comment]
Images #220 completed, PR ready for review:
https://github.com/centrica-engineering/nucleus-docs/pull/229

**Comment by RobTobias123** [comment]
Additional images found that need updating in the Patterns section: #236
