### ISSUE TITLE
[EPIC] New Docs 

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#243]
## Outcome

Our docs live on our new platform (Astro) with a redesigned structure.

## Scope

- [x] https://github.com/centrica-engineering/nucleus/issues/624
- [x] #244
- [x] #256
- [x] Move assets to new docs
  - [x] #263
  - [x] #254
   - [x] #287
  - [x] #288
  - [x] #289
- [x] Creative exploration 
  - [ ] #253
  - [x] #303
  - [x] #279
  - [x] #280
- [x] #245
- [x] #246
  - [x] #272 - See this PR: [#3318](https://github.com/ConnectedHomes/nucleus/pull/3318)
- [x] #247
- [ ] #248
- [x] Additional content
  - [x] #249
  - [x] #250
  - [x] #251
  - [x] #252
- [ ] #309
- [x] #255

**Comment by andij** [comment]
Closing this Epic ticket as the majority of items are complete.

- Any incomplete items have been moved to: #473
