### ISSUE TITLE
[Epic] Populate manual content

### ISSUE THREAD

**Issue by PtitBen** [centrica-engineering/nucleus-docs#247]
## Outcome

Each component has all the manual content required for a full doc

## Scope

Sections to be completed for all components. 

 ### Overview

- [x] Purpose  (PR: #273 )
- [x] #284
- [x] #315
- [x] #314

 ### Guidance

- [x] Types (text based content - for HTML examples see above links)
- [x] Content Guidance See #263 
- [x] Examples (snippet + preview) - see #284 

 ### Implementation

- [x] Specs notes (+ tables) See #326  and #328 
- [x] #294
- [x] Best Practices (text content)
- [x] Accessibility

(This approach has changed from completing each component individually. Following the discussion on 6 December it was agreed we can proceed with creating 1 file of content with all components covered for each section to allow work on the technical aspect to proceed in parallel until ready to unite).

**Comment by RobTobias123** [comment]
The 'Purpose' section PR was created and an initial temp file was added. Content is now being added. 
https://github.com/centrica-engineering/nucleus-docs/pull/273

**Comment by RobTobias123** [comment]
Following review and feedback this morning:

- Component names in purposes follow the same simpler, clearer convention of 'Use ns-xyz to...' instead of 'Use the XYZ component to...'
- All component names in purpose are displayed using back-ticks
- An example of the automated deprecation message as a Starlight 'caution aside' also contains an example of the back-ticked display of the component name with link. (Is this too specific?)
- Image references removed (image/examples will be part of the overview, not purpose section)
- Parsed corrected to passed
- Checked the contrast ratio of the back-tick text-background and text and it appears it needs changing in the custom.css as not quite enough contrast (light mode) for the size (needs to be 4.5:1):

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/81d3b230-6798-4881-9d3b-e6c838adf29e)

![Image](https://github.com/centrica-engineering/nucleus-docs/assets/78355810/909034cc-df6d-46a3-9d91-8b905c18dd67)

**Comment by RobTobias123** [comment]
Following our team's conversation this morning it was decided that it was not necessary to repeat the component names in the 'purpose' one-liners (which will be assumed to reside in the component js and be pulled into the docs to automate).

PR for review please: https://github.com/centrica-engineering/nucleus-docs/pull/273

**Comment by RobTobias123** [comment]
Updated purpose text to not refer to 'We use...' to retain correct focus.
Reworded ns-alert secondary paragraph to be more generic and consistent with others. 
Adjusted and checked custom.css colour values for light and dark to ensure 'Deprecated' pill and back-ticked names meet contrast ratio requirements.

**Comment by RobTobias123** [comment]
I've started adding the index pages and adding the updated purposes as discussed earlier today with Mekala, I've just worked on ns-a... so far and amended what was already there or added new ones based on the example set of pages Drew created. 

Note that on ns-article, I have included that standard deprecation message we mentioned. I've added it to the top of all of that component's pages as it would need to be clear on all pages if the user hadn't arrived via the Overview page etc.  I think I'll flesh out this "ns-a..." category with all the content in the right places for now before rinse and repeat for the others. 

I have also noticed we have Purpose/Types on the Overview page, we also have Types under Guidance on the default structure ticket #245 but I will assess as I go in case that feels like duplication...

**Comment by RobTobias123** [comment]
Added ns-tabs overview and example and amalgamated ns-tab into it. Branch feature/tab-into-tabs - this will negate the need for a separate ns-tab page as that component is never used in isolation. 

We will be looking to do similar with ns-timeline and ns-timeline-event.

**Comment by RobTobias123** [comment]
Creating component HTML files for docs snippets "_examples" based on Storybook. Agreed approach is to name each file as its type. The default is standard.html, others may have appendages conjoined with underscores, eg. direct_link.html and direct_button.html. 

Accordion to CTA done so far and saved locally for inclusion once Drew has completed work on his branch affecting the file structure. 

Point to note: The ns-cta has many types and an example of each that shows loading, or within form etc. My thoughts were that perhaps that could be a configuration option? Eg. a checkbox for 'Loading state' etc? (similar to  how we used  'knobs' or 'controls' in storybook?)

**Comment by RobTobias123** [comment]
All HTML _examples for general components (accordion to video) have been created and saved locally (as above). Form components _examples now in progress.

**Comment by RobTobias123** [comment]
All HTML _examples for form components (appointment-picker to selector) have been created and saved locally (as above). 
I have marked a couple as I have some questions that I will compile for addressing in the next docs catch up (tomorrow).

deprecated and nsx experiences _examples now in progress.

**Comment by RobTobias123** [comment]
HTML _examples for deprecated and nsx experiences have been created and saved locally.

**Comment by RobTobias123** [comment]
**Observation:** 

Some snippet examples use British Gas type content, others in Lorem Ipsum. The components are visually British Gas style and these particular set of docs I understand are for British Gas. So I am anticipating a similar but nuanced set for any other brand that may adopt Nucleus, rather than a one-size-fits-all, vanilla Nucleus set of docs.

**Question:**

It could be better if we make it all consistent, but which way? Having content relevant to the business using it might illustrate the example usage well, but is it taken too literally, and just copied without changes being considered? Using a random irrelevant topic for content has also been shown to confuse. And using Lorem Ipsum may seem too vague.

What is the consensus on this?
