### ISSUE TITLE
[Docs content] HTML Examples

### ISSUE THREAD

**Issue by RobTobias123** [centrica-engineering/nucleus-docs#284]
### Outcome
A refined set of HTML examples for each component type and state as required, to pull into the docs where the legacy version used screenshots. Enables users to understand, view or copy the snippet for use in a prototype from one resource, without going to Storybook for a more efficient workflow.

### Scope
- [x] Obtain all snippets currently used in storybook and save a local set for modifying
- [x] Ascertain the consistent use of placeholder text vs BG example text
- [x] Clean up HTML spacing indentation and formatting, removing unnecessary attributes eg. because default.
- [x] Apply agreed naming convention (hyphens not underscores) (standard + type + state etc)

Update HTML example files (standard + type + state etc) and check visuals in playground for each component:
- [x] ns-accordion
- [x] ns-alert
- [x] ns-appointment-picker
- [x] ns-article
- [x] ns-content
- [x] ns-calendar
- [x] ns-card
- [x] ns-caveat
- [x] ns-column
- [x] ns-content
- [x] ns-cta
- [x] ns-datepicker
- [x] ns-download
- [x] ns-editorial
- [x] ns-expander
- [x] ns-fieldset
- [x] ns-footer
- [x] ns-form
- [x] ns-form-group
- [x] ns-header
- [x] ns-highlighter
- [x] ns-icon
- [x] ns-illustration
- [x] ns-image
- [x] ns-inputter
- [x] ns-landmark
- [x] ns-live
- [x] ns-lockup
- [x] ns-panel
- [x] ns-password <-- QUESTION ON THIS: https://github.com/centrica-engineering/nucleus-docs/issues/284#issuecomment-1884764752
- [x] ns-pill
- [x] ns-price
- [x] ns-product-card
- [x] ns-progress <-- QUESTION ON THIS: https://github.com/centrica-engineering/nucleus-docs/issues/284#issuecomment-1884918993
- [x] ns-selector <-- QUESTION ON THIS: https://github.com/centrica-engineering/nucleus-docs/issues/284#issuecomment-1884951239
- [x] ns-skeleton
- [x] ns-skyline
- [x] ns-standout
- [x] ns-tab
- [x] ns-table
- [x] ns-tabs
- [x] ns-testimonial
- [x] ns-timeline
- [x] ns-timeline-event
- [x] ns-video
- [x] nsx-address-selector
- [x] nsx-footer
- [x] nsx-header
- [x] nsx-markting-consent
- [x] nsx-product-card-overview

**Comment by RobTobias123** [comment]
Following discussions and initial trials, we decided the following:

- All component examples should use 'Hipster Ipsum' placeholder text, unless it is an intrinsic part of that component (eg. 'select a date' on the ns-datepicker). This means that the text will not imply any content and that any description can be made in the docs itself. It is also more scalable should we use for another brand, meaning less maintenance requirements in the future.
- All experiences will include the relative example content as specific to that brand. eg. ns-header component will show placeholder text, whereas nsx-header (the British Gas experience) would should BG examples of links/content etc. Because experiences may be particular to each brand we feel this is the right approach for now.

**Comment by RobTobias123** [comment]
LInk to the playground index (WIP) displaying a page of examples for visual reference of each component/experience using the modified HTML. (Please do not edit yet).

https://playground.nucleus.design/?t=index.html#project=e20d2a4b-b286-40f0-a297-fade0aee3f16

**Comment by RobTobias123** [comment]
ns-accordion https://playground.nucleus.design/?t=ns-accordion.html#project=4825bb77-bbef-48cc-a13f-1ae480f4ff59

**Comment by RobTobias123** [comment]
ns-alert https://playground.nucleus.design/?t=ns-alert.html#project=76c44d2b-fa26-41a1-8e5c-31175c37def5

**Comment by RobTobias123** [comment]
ns-appointment-picker https://playground.nucleus.design/?t=ns-appointment-picker.html#project=7fdd8944-3bf3-4b6d-b06f-592078314869

**Comment by RobTobias123** [comment]
ns-content https://playground.nucleus.design/?t=ns-content.html#project=6c364764-3479-43f3-9f2b-e1cc4f6dbafa

**Comment by RobTobias123** [comment]
ns-article https://playground.nucleus.design/?t=ns-article.html#project=264556f1-7c42-410e-ba77-e8e6a6599e71

**Comment by RobTobias123** [comment]
ns-calendar https://playground.nucleus.design/?t=ns-calendar.html#project=dcfeb7d6-9619-407d-9f67-5cbd0a6fca7c

**Comment by RobTobias123** [comment]
ns-card https://playground.nucleus.design/?t=ns-card.html#project=b3cf15c1-5fea-4f12-9629-ce9e9aff8f85

**Comment by RobTobias123** [comment]
ns-caveat https://playground.nucleus.design/?t=ns-caveat.html#project=b44a2a1e-f9fd-44d7-a10b-e2876b4d817c

**Comment by RobTobias123** [comment]
ns-column https://playground.nucleus.design/?t=ns-column.html#project=710ef4c9-035a-4138-bba5-c97cb8b21698

**Comment by RobTobias123** [comment]
ns-content https://playground.nucleus.design/?t=ns-content.html#project=b207f827-abf3-4710-b97f-3ed473c1ce95

**Comment by RobTobias123** [comment]
ns-cta https://playground.nucleus.design/?t=ns-cta.html#project=96f13c45-fb64-4817-b33d-5a63689e563f

**Comment by RobTobias123** [comment]
ns-datepicker https://playground.nucleus.design/?t=ns-datepicker.html#project=75dd9d01-2498-40a8-9027-0f8102493c9d

**Comment by RobTobias123** [comment]
ns-download https://playground.nucleus.design/?t=ns-download.html#project=169ba0c6-11ea-4719-bec8-0420c7e3c46f

**Comment by RobTobias123** [comment]
ns-editorial https://playground.nucleus.design/?t=ns-editorial.html#project=11b2a654-3597-4647-8e4d-f0eb32dd1548

**Comment by RobTobias123** [comment]
ns-expander https://playground.nucleus.design/?t=ns-expander.html#project=04801a37-8d55-4ef1-861e-3d98faee0d30

**Comment by RobTobias123** [comment]
ns-footer https://playground.nucleus.design/?t=ns-footer.html#project=cd941106-e04e-4df3-b1b5-507cf8600523

**Comment by RobTobias123** [comment]
ns-form-group https://playground.nucleus.design/?t=ns-form-group.html#project=7c518382-6f2c-4cbc-b331-963d8976d9f2

**Comment by RobTobias123** [comment]
ns-header https://playground.nucleus.design/?t=ns-header.html#project=88aa3f7c-27a1-4976-a774-4b81ca044a33

**Comment by RobTobias123** [comment]
ns-highlighter https://playground.nucleus.design/?t=ns-highlighter.html#project=c5a7e6ec-bf67-4e75-b326-962a9b38a7d6

**Comment by RobTobias123** [comment]
ns-icon https://playground.nucleus.design/?t=ns-icon.html#project=9998c124-a6cc-4a56-b79b-70150f281c63

**Comment by RobTobias123** [comment]
ns-illustration https://playground.nucleus.design/?t=ns-illustration.html#project=693a2bf0-1446-46c7-a6ea-c8998a2c3284

**Comment by RobTobias123** [comment]
ns-image https://playground.nucleus.design/?t=ns-image.html#project=750d9bca-8aeb-4dba-a8e6-22e768ffbfc0

**Comment by RobTobias123** [comment]
ns-inputter https://playground.nucleus.design/?t=ns-inputter.html#project=8f0fbe46-b715-4606-af4f-f209280d7782

**Comment by RobTobias123** [comment]
ns-landmark https://playground.nucleus.design/?t=ns-landmark.html#project=3188bcde-c49c-42d1-9025-868538a6e43d

**Comment by RobTobias123** [comment]
ns-live https://playground.nucleus.design/?t=ns-live.html#project=9035efd0-1237-423a-9946-df7931f74c27

**Comment by RobTobias123** [comment]
ns-lockup https://playground.nucleus.design/?t=ns-lockup.html#project=bb6a78eb-f486-4461-9588-64df0d02d63f

**Comment by RobTobias123** [comment]
ns-panel https://playground.nucleus.design/?t=ns-panel.html#project=42d27ef3-1501-4a8e-9cd1-e88df83113aa

**Comment by RobTobias123** [comment]
ns-pill https://playground.nucleus.design/?t=ns-pill.html#project=007cad4e-ac25-4536-9295-7429c5bfbbb2

**Comment by RobTobias123** [comment]
ns-price https://playground.nucleus.design/?t=ns-price.html#project=3077c09b-fb00-4cba-850e-de89de2d84a0

**Comment by RobTobias123** [comment]
ns-product-card https://playground.nucleus.design/?t=ns-product-card.html#project=35a20061-0c1c-44e4-b502-7f7e24f8a1ab

**Comment by RobTobias123** [comment]
ns-progress https://playground.nucleus.design/?t=ns-progress.html#project=3570b832-a1b2-4746-bc31-980fc8505280

Question: On the Form type, Buttons Back and Next are not part of the component and don't work outside of Storybook. Should we omit the buttons in this form.html example?

**Comment by RobTobias123** [comment]
ns-selector https://playground.nucleus.design/?t=ns-selector.html#project=0f62bcc9-971c-483e-8eea-3072a38d8941

Question: All these are wrapped in ns-inputter with a label. Is that required for this purpose?

**Comment by RobTobias123** [comment]
ns-skeleton https://playground.nucleus.design/?t=ns-skeleton.html#project=31361138-6d8e-4aa2-97ea-34967d169560

**Comment by RobTobias123** [comment]
ns-skyline https://playground.nucleus.design/?t=ns-skyline.html#project=34b852cd-cfc0-45fd-a729-7e97e8b194ad

**Comment by RobTobias123** [comment]
ns-standout https://playground.nucleus.design/?t=ns-standout.html#project=9205cc3f-0a60-42ba-a43c-76d3cbfc458b

**Comment by RobTobias123** [comment]
ns-tab https://playground.nucleus.design/?t=ns-tab.html#project=ece1daa7-57a0-4b7d-be72-48948f8f3e31

**Comment by RobTobias123** [comment]
ns-table https://playground.nucleus.design/?t=ns-table.html#project=72c4b479-5be3-487b-a0e1-7a9137b03381

**Comment by RobTobias123** [comment]
ns-tabs https://playground.nucleus.design/?t=ns-tabs.html#project=e081761d-eabc-4281-aabf-9fd18329639b

**Comment by RobTobias123** [comment]
ns-testimonial https://playground.nucleus.design/?t=ns-testimonial.html#project=fae5b9ce-f7d1-4a67-940a-78a965bc34d0

**Comment by RobTobias123** [comment]
ns-timeline https://playground.nucleus.design/?t=ns-timeline.html#project=bb064d23-f691-4d79-96cb-b66bb21ececb

**Comment by RobTobias123** [comment]
ns-timeline-event https://playground.nucleus.design/?t=ns-timeline-event.html#project=a8b8cf57-ee03-427b-a541-297fc0f4d967

**Comment by RobTobias123** [comment]
ns-video https://playground.nucleus.design/?t=ns-video.html#project=e1d83b31-dc59-44b4-9cac-01c47e9f3547

**Comment by RobTobias123** [comment]
nsx-address-selector https://playground.nucleus.design/?t=nsx-address-selector.html#project=3f9a1141-3176-44d5-88c1-c9fc3d9af618

**Comment by RobTobias123** [comment]
nsx-footer https://playground.nucleus.design/?t=nsx-footer.html#project=4a54e0cc-22e5-42c0-88f3-15a2f2ab7f6f

**Comment by RobTobias123** [comment]
nsx-footer https://playground.nucleus.design/?t=nsx-footer.html#project=e4b960b5-7c4e-4717-bf4b-369eb0ea0fb4

**Comment by RobTobias123** [comment]
nsx-marketing-consent https://playground.nucleus.design/?t=nsx-marketing-consent.html#project=d5cbbd44-cac4-4436-bc04-860582a3e7d4

**Comment by RobTobias123** [comment]
nsx-product-card-overview https://playground.nucleus.design/?t=nsx-product-card-overview.html#project=e1aecfc2-f723-4dd3-90b8-c4ca5305de5a
