### ISSUE TITLE
[Epic] - Docs v3.0 beta

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#348]
```[tasklist]
### Bugs
- [x] [Bug] Heading links - on hover the icon effects the height #350
- [x] [Bug] Content guidance - the table heading is not being hidden #352
- [x] [Bug] Sidebar - position when no Section tabs #356
- [x] [Bug] Configurator - Default / Anonymous slot textarea is populating the content
- [x] [Bug] Deployed CSS inconsistent with local CSS
```

```[tasklist]
### Priority high
- [x] Configurator - define layout and styles #320
- [x] Specification - User testing #328 #326  - user testing completed
- [x] Listed items - Description list and table combined #326
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/358
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/371
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/366
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/367
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/310
- [x] Examples - Use `@placement` to set up the Examples preview with or without ns-panel https://github.com/centrica-engineering/nucleus-docs/pull/395
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/353
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/354
- [x] Badges - 'New' manually managed - data.json file - combine with astro.config https://github.com/centrica-engineering/nucleus-docs/pull/396
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/365
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/429
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/419
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/359
- [x] Masthead - Complete SVG illustrations #287
- [x] Masthead - improve the mini-masthead when there's no illustration - default fallback #356
- [x] Masthead - Place 'category' in the namespace area
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/369
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/373
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/374
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/387
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/423
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/432
```

```[tasklist]
### Priority medium
- [x] Footer - Use a template for 'Report a content issue' -> 'Report a problem'
- [x] Homepage - List of recently updated Docs pages
- [x] Content guidance - Introduce a style to the Key (round and pink)
```

```[tasklist]
### Priority low
- [ ] ~Search - position and size of the search field and overlay~
```

```[tasklist]
## No priority
- [x] Banner for communication and announcements
- [x] Configurator - Header Logo
```

**Comment by andij** [comment]
Close this ticket as the Beta has been released.

Moved outstanding items to #473
