### ISSUE TITLE
[Epic] - Docs backlog

### ISSUE THREAD

**Issue by andij** [centrica-engineering/nucleus-docs#473]
```[tasklist]
### Bugs
- [ ] [Bug] Specification - enable deep-linking for `<h4>` headings
- [ ] [Bug] Content - deep-link not matching heading due to Example iframe
- [ ] [Bug] Page navigation - first item selected on page-load #442
```

```[tasklist]
### Backlog
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/363
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/364
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/372
- [ ] https://github.com/centrica-engineering/nucleus-docs/issues/383
- [ ] Include accessibility checks on the build step for HTML assets
- [ ] Configurator - Accessibility include colour blindness filters
- [ ] Masthead - Stable - Alpha - Beta (badges) - include `@release` into JSDocs https://github.com/ConnectedHomes/nucleus/pull/3366
- [ ] Examples - attend to the radius of the preview and code snippet
- [ ] Code snippet - Show 'copy to clipboard' label
- [ ] Examples - Deep linking tabs with query string
- [ ] `ns-header` and `nsx-header` are difficult to distinguish between
- [ ] [Ability to copy deep-link URL when clicking on a heading's link-icon | nucleus-docs#384](https://github.com/centrica-engineering/nucleus-docs/issues/384)
- [ ] [Button style | nucleus-docs#409](https://github.com/centrica-engineering/nucleus-docs/issues/409)
- [ ] Consider different icons - to include more fun (e.g. rocket for Do's)
- [ ] Show version change by clicking on the version number
- [ ] Homepage - Latest release notes (automated version)
- [ ] Configurator - component masthead svg
- [ ] Configurator - Theme
- [ ] Update README.md
```

**Comment by andij** [comment]
## Observations

- [ ] Timeline Event - 'additional content' should be 'Anonymous slot'
- [ ] Change aspect ratios that are 4:3 to `4 / 3`
- [ ] Remove references to Sketch and Figma, where it can be generalised
- [ ] `ns-selector` the Heading is missing from the Guidance for 'with image'
- [ ] `ns-selector` interchangeable use of 'decoration' and 'illustration'
- [ ] Consistent use of `standard` when displaying Examples
      E.g:
        `ns-cta` - Standard (Direct) / Text
        `ns-cta` - Direct (standard) / Text
- [ ] Remove the reference to Highlighter in `ns-alert`, as this is the Standard type
- [ ] Further documentation on `ns-skeleton` and how `slot` influences it, take note of the Specification as it appears to misrepresent the `type`
- [ ] Use title case across the site - noted in the Guidance tables
- [ ] Consistent use of backticks around component names - `ns-table` or ns-table or `<ns-table>`
      Consider how the components that are links compliment this
      - [ ] Should we remove the `type` from Specification if it is:
      `type` - Property - `type` - Type - `string` - Default - `standard`
- [ ] Write any missing Do and Don't - `nsx-address-selector`
- [ ] Remove all hyperlinks from Examples to britishgas.co.uk and /this/path/file.name
- [x] All instances of JPEG replaced with WebP
- [ ] Datepicker `masked` Example missing
- [ ] Marketing consent is missing Guidance Image and Key table
- [ ] Something is up with the Permitted tags here: `/components/ns-article#specification-slots`
- [ ] Include 'open in new tab' for Example
- [ ] Rewrite the Guidance for `ns-calendar`

**Comment by RobTobias123** [comment]
### Idea based on feedback receieved - 'Jargon-buster' 
A page to be added to the Docs - probably under 'Guidelines', as a reference type page that is just an Alphabetical list/glossary of terms and acronyms we use so they can be easily understood. Possibly searchable or indexed/anchored.

Feedback that sparked the idea (MS Forms capture from Docs):
![Image](https://github.com/user-attachments/assets/a79cb6ad-06fc-43b8-bf8d-c2025613c14e)
