### ISSUE TITLE
Content - update all JSDocs content - [incl test automation scripts]

### ISSUE THREAD

**Issue by MekalaNagarajan-Centrica** [centrica-engineering/nucleus-docs#518]
## Outcome
To update the JSDocs for attributes, properties, slots, and events in all the components.

### Scope
- Attributes / Properties
- Slots
- Events
- [ ] update automation script to verify the availability of all descriptions.

```[tasklist]
### Tasks
- [x] Accordion https://github.com/ConnectedHomes/nucleus/pull/3386
- [x] Action link https://github.com/ConnectedHomes/nucleus/pull/3387
- [x] Alert https://github.com/ConnectedHomes/nucleus/pull/3404
- [x] Appointment picker https://github.com/ConnectedHomes/nucleus/pull/3388
- [x] Article https://github.com/ConnectedHomes/nucleus/pull/3427
- [x] Calendar https://github.com/ConnectedHomes/nucleus/pull/3389
- [x] Card https://github.com/ConnectedHomes/nucleus/pull/3390
- [x] Caveat https://github.com/ConnectedHomes/nucleus/pull/3391
- [x] Column https://github.com/ConnectedHomes/nucleus/pull/3392
- [x] Content https://github.com/ConnectedHomes/nucleus/pull/3427
- [x] CTA https://github.com/ConnectedHomes/nucleus/pull/3394
- [x] Date Time https://github.com/ConnectedHomes/nucleus/pull/3395
- [x] Date picker https://github.com/ConnectedHomes/nucleus/pull/3396
- [x] Download https://github.com/ConnectedHomes/nucleus/pull/3397
- [x] Editorial https://github.com/ConnectedHomes/nucleus/pull/3398
- [x] Expander https://github.com/ConnectedHomes/nucleus/pull/3401
- [x] Fieldset https://github.com/ConnectedHomes/nucleus/pull/3399
- [x] Form https://github.com/ConnectedHomes/nucleus/pull/3410
- [x] Form Group https://github.com/ConnectedHomes/nucleus/pull/3399
- [x] Footer https://github.com/ConnectedHomes/nucleus/pull/3403
- [x] Header https://github.com/ConnectedHomes/nucleus/pull/3400
- [x] Highlighter https://github.com/ConnectedHomes/nucleus/pull/3404
- [x] Icon https://github.com/ConnectedHomes/nucleus/pull/3407
- [x] Illustration https://github.com/ConnectedHomes/nucleus/pull/3407
- [x] Image https://github.com/ConnectedHomes/nucleus/pull/3409
- [x] Inputter https://github.com/ConnectedHomes/nucleus/pull/3410
- [x] Landmark https://github.com/ConnectedHomes/nucleus/pull/3412
- [x] Live https://github.com/ConnectedHomes/nucleus/pull/3413
- [x] Lockup https://github.com/ConnectedHomes/nucleus/pull/3414
- [x] Address Selector https://github.com/ConnectedHomes/nucleus/pull/3415
- [x] Nsx Footer https://github.com/ConnectedHomes/nucleus/pull/3403
- [x] Nsx Header https://github.com/ConnectedHomes/nucleus/pull/3400
- [x] Marketing Consent https://github.com/ConnectedHomes/nucleus/pull/3419
- [x] Product card overview https://github.com/ConnectedHomes/nucleus/pull/3426
- [x] Panel https://github.com/ConnectedHomes/nucleus/pull/3421
- [x] Password https://github.com/ConnectedHomes/nucleus/pull/3435
- [x] Pill https://github.com/ConnectedHomes/nucleus/pull/3421
- [x] Price https://github.com/ConnectedHomes/nucleus/pull/3424
- [x] Product Card https://github.com/ConnectedHomes/nucleus/pull/3420
- [x] Progress https://github.com/ConnectedHomes/nucleus/pull/3422
- [x] Selector https://github.com/ConnectedHomes/nucleus/pull/3420
- [x] Skeleton https://github.com/ConnectedHomes/nucleus/pull/3432
- [x] Skyline https://github.com/ConnectedHomes/nucleus/pull/3433
- [x] Standout https://github.com/ConnectedHomes/nucleus/pull/3431
- [x] Tab https://github.com/ConnectedHomes/nucleus/pull/3434
- [x] Table https://github.com/ConnectedHomes/nucleus/pull/3436
- [x] Tabs https://github.com/ConnectedHomes/nucleus/pull/3434
- [x] Testimonial https://github.com/ConnectedHomes/nucleus/pull/3428
- [x] Timeline https://github.com/ConnectedHomes/nucleus/pull/3429
- [x] Timeline Event https://github.com/ConnectedHomes/nucleus/pull/3429
- [x] Video https://github.com/ConnectedHomes/nucleus/pull/3430
```

**Comment by MekalaNagarajan-Centrica** [comment]
All PRs https://github.com/ConnectedHomes/nucleus/pulls?q=is%3Apr+is%3Aopen+head%3Ajsdoc
